// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: swap.proto

package swap

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// SwapServiceService defines service.
type SwapServiceService interface {
	// Swap 执行切换操作
	Swap(ctx context.Context, req *SwapRequest) (*SwapResponse, error)
}

func SwapServiceService_Swap_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SwapRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SwapServiceService).Swap(ctx, reqbody.(*SwapRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// SwapServiceServer_ServiceDesc descriptor for server.RegisterService.
var SwapServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "swap.SwapService",
	HandlerType: ((*SwapServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/swap.SwapService/Swap",
			Func: SwapServiceService_Swap_Handler,
		},
	},
}

// RegisterSwapServiceService registers service.
func RegisterSwapServiceService(s server.Service, svr SwapServiceService) {
	if err := s.Register(&SwapServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("SwapService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedSwapService struct{}

// Swap 执行切换操作
func (s *UnimplementedSwapService) Swap(ctx context.Context, req *SwapRequest) (*SwapResponse, error) {
	return nil, errors.New("rpc Swap of service SwapService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// SwapServiceClientProxy defines service client proxy
type SwapServiceClientProxy interface {
	// Swap 执行切换操作
	Swap(ctx context.Context, req *SwapRequest, opts ...client.Option) (rsp *SwapResponse, err error)
}

type SwapServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewSwapServiceClientProxy = func(opts ...client.Option) SwapServiceClientProxy {
	return &SwapServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *SwapServiceClientProxyImpl) Swap(ctx context.Context, req *SwapRequest, opts ...client.Option) (*SwapResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/swap.SwapService/Swap")
	msg.WithCalleeServiceName(SwapServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SwapService")
	msg.WithCalleeMethod("Swap")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SwapResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
